global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 0.2
    transform_tolerance: 0.5
    publish_frequency: 0.2
    static_map: true
    inf_is_valid: true
    inflation_radius: 0.4
    cost_scaling_factor: 15
    footprint_padding: 0.16
    footprint: [[0.52,-0.20],[0.50,-0.24],[-0.13, -0.24],[-0.15, -0.20],[-0.15, 0.20],[-0.13, 0.24],[0.50,0.24],[0.52,0.20]]
    obstacle_range: 4.0
    raytrace_range: 5.0
    max_obstacle_height: 0.6
    min_obstacle_height: 0.00
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
