TebLocalPlannerROS:
    odom_topic: odom
    map_frame: /odom

    # Trajectory
    teb_autosize: true
    dt_ref: 0.2
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: true
    max_global_plan_lookahead_dist: 3.0
    feasibility_check_no_poses: 5
    allow_init_with_backwards_motion: true
    min_samples: 3

    # Robot
    max_vel_x: 0.35
    max_vel_x_backwards: 0.15
    max_vel_theta: 0.6
    acc_lim_x: 0.25
    acc_lim_theta: 0.3
    min_turning_radius: 0.0
    wheelbase: 0.0
    footprint_model:     # types: "point", "circular", "two_circles", "line", "polygon"
        type: "polygon"
        radius: 0.18 # for type "circular"
        line_start: [-0.1, 0.0] # for type "line"
        line_end: [0.15, 0.0] # for type "line"
        front_offset: 0.2 # for type "two_circles"
        front_radius: 0.2 # for type "two_circles"
        rear_offset: 0.2 # for type "two_circles"
        rear_radius: 0.2 # for type "two_circles"
        vertices: [[0.52,-0.20],[0.50,-0.24],[-0.13, -0.24],[-0.15, -0.20],[-0.15, 0.20],[-0.13, 0.24],[0.50,0.24],[0.52,0.20]] # for type "polygon"

    # GoalTolerance
    xy_goal_tolerance: 0.05
    yaw_goal_tolerance: 0.1
    free_goal_vel: false

    # Obstacles
    global_plan_viapoint_sep: 0.3
    min_obstacle_dist: 0.1
    costmap_obstacles_behind_robot_dist: 0.10
    obstacle_poses_affected: 30
    costmap_converter_spin_thread: true
    costmap_converter_rate: 5
    include_dynamic_obstacles: true
    include_costmap_obstacles: false

    # Optimization
    no_inner_iterations: 7
    no_outer_iterations: 5
    penalty_epsilon: 0.1
    weight_max_vel_x: 0.2
    weight_max_vel_theta: 0.1
    weight_acc_lim_x: 0.5
    weight_acc_lim_theta: 0.5
    weight_kinematics_nh: 800
    weight_kinematics_forward_drive: 0.25
    weight_kinematics_turning_radius: 0.0
    weight_optimaltime: 1.0
    weight_obstacle: 200.0
    weight_viapoint: 4.0
    inflation_dist: 0.4
    weight_dynamic_obstacle: 10 # not in use yet
    alternative_time_cost: false # not in use yet

    # Homotopy Class Planner
    enable_homotopy_class_planning: true
    enable_multithreading: true
    simple_exploration: false
    max_number_classes: 4
    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 6
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.45
    visualize_hc_graph: false
